##  CONFIG
outDir: "results/2025_GM12878_K562_eQTLs_better_Kendall"
scratchDir: "$SCRATCH/Data"
methodsTable: "config/config_methods.tsv"
predictionsTable: "config/new_subset_predictions.tsv" #subset_predictions.tsv
methods: [scE2G_multiome, scE2G_ATAC, ArchR, Signac, Cicero, SCENT, pgBoost, scABC, Kendall, ABC_distanceToTSS] # , SCARlink, FigR
eQTLVariants: "/oak/stanford/groups/engreitz/Users/sheth/Data/eQTL_Catalogue_v7/results/2024_0623_coarse_tissues/eQTL_catalogue_v7.processed.PIP0.5.tsv.gz" # columns: chr,start,end,variant_id,gene_hgnc,tissue,pip - I also have an extra gene_ensembl col

## RESOURCE / REFERENCE FILES
baseDir: "/oak/stanford/groups/engreitz/Users/kaybrand/Benchmark/eQTLEnrichment"
# Genome annotations
chrSizes: "resources/genome_annotation/GRCh38_EBV.chrom.sizes.tsv" 
partition: "resources/genome_annotation/PartitionCombined.bed" 
TSS_reference: "resources/genome_annotation/CollapsedGeneBounds.hg38.intGENCODEv43.TSS500bp.bed6" 
# Background variants
bgVariants: "/oak/stanford/groups/engreitz/Users/sheth/Data/share/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted"

## PARAMETERS (leave unmodified)
distances: [10, 100, 250, 1000] # in kb
recalls: [0.03, 0.05, 0.1] # to compare enrichments
thresholdPIP: 0.5
thresholdPval: 0.05
nThresholdSteps: 50





